question_data = [
    {"text": "A slug's blood is green.", 
        "answer": "True"},
    {"text": "The loudest animal is the African Elephant.",
        "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", 
        "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", 
        "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", 
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", 
        "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", 
        "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", 
        "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", 
        "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", 
        "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", 
        "answer": "True"}
]

question_data1 = [
    {"text": 'AMCs "The Walking Dead", Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.',
        "answer": "False"},
    {"text": 'The common software-programming acronym "I18N" comes from the term "Interlocalization".',
        "answer": "False"},
    {"text": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
        "answer": "False"},
    {"text": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
        "answer": "False"},
    {"text": "Super Mario Bros. was released in 1990.",
        "answer": "False"},
    {"text": "In World War II, Hawker Typhoons served in the Pacific theater.",
        "answer": "False"},
    {"text": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
        "answer": "False"},
    {"text": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
        "answer": "True"},
    {"text": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
        "answer": "True"},
    {"text": "The General Motors EV1 was the first street-legal production electric vehicle.",
        "answer": "False"},
    {"text": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
        "answer": "True"},
    {"text": 'Klingons once had a period of Democracy in their history, they referred to it as the "Dark Times".',
        "answer": "True"},
    {"text": 'The Roman god "Jupiter" was first known as "Zeus" to the Greeks.',
        "answer": "True"},
    {"text": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
        "answer": "True"},
    {"text": 'Musical artist, Future, collaborated with Kendrick Lamar for the song: "Mask Off".',
        "answer": "True"},
    {"text": 'The movie "Tron" received an Oscar nomination for Best Visual Effects.',
        "answer": "False"},
    {"text": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
        "answer": "True"},
    {"text": "Night on Bald Mountain was one of the musical pieces featured in Disney's 1940's film Fantasia.",
        "answer": "True"},
]
